# Generated by Django 6.0.3 on 2026-05-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipplacement',
            name='description',
            field=models.TextField(default='No description provided'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internshipplacement',
            name='duration',
            field=models.CharField(default='No description provided', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internshipplacement',
            name='location',
            field=models.CharField(default='No description provided', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internshipplacement',
            name='position',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internshipplacement',
            name='stipend',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
