# Generated by Django 6.0.3 on 2026-04-23 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipplacement',
            name='academic_supervisor',
            field=models.ForeignKey(limit_choices_to={'role': 'supervisor'}, on_delete=django.db.models.deletion.CASCADE, related_name='supervised_internships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='internshipplacement',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_internships', to=settings.AUTH_USER_MODEL),
        ),
    ]
