# Generated by Django 6.0.3 on 2026-04-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklylog',
            name='status',
            field=models.CharField(choices=[('draft ', 'Draft'), ('submitted', 'Submitted'), ('reviewed ', 'Reviewed'), ('approved  ', 'Approved '), ('rejected  ', 'Rejected ')], default='Pending', max_length=10),
        ),
    ]
