# Generated by Django 6.0.3 on 2026-04-23 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internshipplacement',
            old_name='academic_supervisor',
            new_name='academic_supervisor_id',
        ),
    ]
