# Generated by Django 6.0.3 on 2026-05-07 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklylog',
            name='week_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
