# Generated by Django 6.0.3 on 2026-04-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Custom User', 'verbose_name_plural': 'Custom Users'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('work_supervisor', 'Workplace Supervisor'), ('acad_supervisor', 'Academic Supervisor'), ('admin', 'Admin')], default='student', max_length=20),
        ),
    ]
