# Generated by Django 6.0.3 on 2026-04-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_weeklylog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklylog',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('approved', 'Approved')], default='draft', max_length=20),
        ),
    ]
