# Generated by Django 6.0.3 on 2026-04-23 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_internshipplacement_academic_supervisor_and_more'),
        ('core', '0002_rename_academic_supervisor_internshipplacement_academic_supervisor_id'),
    ]

    operations = [
    ]
