# Generated by Django 6.0.3 on 2026-05-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_internshipplacement_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issue_type', models.CharField(choices=[('Missing Marks', 'Missing Marks'), ('Exam Result', 'Exam Result')], max_length=20)),
                ('status', models.CharField(default='Open', max_length=20)),
                ('description', models.TextField()),
            ],
        ),
    ]
