# Generated by Django 6.0.3 on 2026-04-23 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_merge_20260423_0726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshipplacement',
            name='academic_supervisor_id',
        ),
        migrations.RemoveField(
            model_name='weeklylog',
            name='student',
        ),
        migrations.AlterField(
            model_name='internshipplacement',
            name='academic_supervisor',
            field=models.ForeignKey(limit_choices_to={'role': 'acad_supervisor'}, on_delete=django.db.models.deletion.CASCADE, related_name='supervised_internships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weeklylog',
            name='challenges',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weeklylog',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('approved', 'Approved')], default='draft', max_length=10),
        ),
    ]
