# Generated by Django 6.0.3 on 2026-04-14 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_placement'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='placement',
            new_name='InternshipPlacement',
        ),
    ]
