# Generated by Django 6.0.3 on 2026-05-07 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_weeklylog_student_and_more'),
        ('core', '0002_weeklylog_week_start_date'),
        ('core', '0003_issue'),
    ]

    operations = [
    ]
