# Generated by Django 6.0.3 on 2026-04-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_internshipplacement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshipplacement',
            name='status',
        ),
        migrations.AddField(
            model_name='internshipplacement',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
