# Generated by Django 6.0.3 on 2026-05-07 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_merge_20260507_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklylog',
            name='week_start_date',
        ),
    ]
